#ifndef ARBTYPE_CONFIG_USER_H
#define ARBTYPE_CONFIG_USER_H

#include "../../config.h"

#define EE_HANDS
#define LED_MATRIX_STARTUP_VAL 100
#define LED_MATRIX_KEYRELEASES
#    define ENABLE_LED_MATRIX_SOLID_REACTIVE_SIMPLE
#    define ENABLE_LED_MATRIX_SOLID_REACTIVE_WIDE
#    define ENABLE_LED_MATRIX_SOLID_REACTIVE_MULTIWIDE
#    define ENABLE_LED_MATRIX_SOLID_REACTIVE_CROSS
#    define ENABLE_LED_MATRIX_SOLID_REACTIVE_MULTICROSS
#    define ENABLE_LED_MATRIX_SOLID_REACTIVE_NEXUS
#    define ENABLE_LED_MATRIX_SOLID_REACTIVE_MULTINEXUS
#    define ENABLE_LED_MATRIX_SPLASH
#    define ENABLE_LED_MATRIX_MULTISPLASH
#define FORCE_NKRO

#undef DEBOUNCE
#define DEBOUNCE 15

#endif
